import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import jwt from "jsonwebtoken";

//styles
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";

//components
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";

//store
import ReduxProvider from "@/app/store/providers/ReduxProvider";

//third-party
import { config } from "@fortawesome/fontawesome-svg-core";
import { AuthProvider } from "./context/AuthContext";
import { DecodedToken } from "./types/user";
import { SocketProvider } from "./store/providers/SocketProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("accessToken")?.value;
  let initialUser = null;

  if (token) {
    try {
      console.log(process.env.ACCESS_TOKEN_SECRET, "dfghk");
      const decoded = jwt.verify(
        token,
        process.env.ACCESS_TOKEN_SECRET!,
      ) as DecodedToken;

      initialUser = {
        _id: decoded?._id,
        name: decoded?.name,
        email: decoded?.email,
        role: decoded?.role,
      };
    } catch {
      initialUser = null;
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <AuthProvider initialUser={initialUser}>
            <SocketProvider>
              <Header />
              {children}
              <Toaster position="top-right" reverseOrder={false} />
              <Footer />
            </SocketProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
