import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Geist, Geist_Mono } from "next/font/google";

//styles
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";

//components
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";

//store
import ReduxProvider from "@/app/store/providers/ReduxProvider";

//third-party
import { config } from "@fortawesome/fontawesome-svg-core";
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <AuthProvider>
            <Header />
            {children}
            <Toaster position="top-right" reverseOrder={false} />
            <Footer />
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
